pipeline:
  deploy:
    image: node:10
    commands:
      - mkdir ~/.ssh
      - echo $${SSH_KEY} > ~/.ssh/id_rsa
      - chmod -R 600 ~/.ssh/pub
      - touch ~/.ssh/known_hosts
      - chmod 600 ~/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
      - git config --global user.email "anton@ohorodnyk.name"
      - git config --global user.name "Anton Ohorodnyk"
      - chmod +x node_modules/.bin/*
      - npm run deploy
    secrets: [ ssh_key ]
    when:
      branch: master
