pipeline:
  deploy:
    image: node:10
    commands:
      - mkdir /root/.ssh
      - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
      - chmod +x node_modules/.bin/*
      - npm run deploy
    secrets: [ ssh_key, ssh_key_public ]
    when:
      branch: master
