pipeline:
  deploy:
    image: node:10
    commands:
      - echo "IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config
      - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
      - mkdir ~/.ssh
      - echo $${SSH_KEY} > ~/.ssh/id_rsa
      - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
      - touch ~/.ssh/known_hosts
      - chmod -R 600 ~/.ssh
      - chmod 700 ~/.ssh/id_rsa.pub
      - chmod +x node_modules/.bin/*
      - npm run deploy
    secrets: [ ssh_key ]
    when:
      branch: master
