pipeline:
  deploy:
    image: node:10
    commands:
      - echo "IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config
      - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
      - mkdir ~/.ssh
      - echo $${SSH_KEY} > ~/.ssh/id_rsa
      - echo $${SSH_KEY_PUBLIC} > ~/.ssh/id_rsa.pub
      - touch ~/.ssh/known_hosts
      - chmod -R 600 ~/.ssh
      - chmod 700 ~/.ssh/id_rsa.pub
      - chmod +x node_modules/.bin/*
      - ssh -vT git@github.com
      - npm run deploy
    secrets: [ ssh_key, ssh_key_public ]
    when:
      branch: master
